# Generated by Django 4.0 on 2022-06-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Malzeme Ismi')),
                ('miktar', models.IntegerField(blank=True, default='0', null=True)),
                ('Materialtype', models.CharField(blank=True, choices=[('kati', 'katı'), ('sivi', 'sıvı'), ('gaz', 'gaz')], default='', max_length=5, null=True, verbose_name='Malzeme Turu')),
                ('kati', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Katı')),
                ('sivi', models.IntegerField(blank=True, default='0', null=True, verbose_name='Sıvı')),
                ('deger', models.IntegerField(blank=True, default='0', null=True, verbose_name='Değer')),
                ('özgünlük', models.IntegerField(blank=True, default='0', null=True, verbose_name='Özgünlük')),
                ('tehlike', models.BooleanField(default=False)),
                ('acidli', models.FloatField(blank=True, default='0', null=True)),
            ],
            options={
                'verbose_name_plural': 'Malzemeler',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Deneyi Adı')),
                ('description', models.FileField(default=None, null=True, upload_to='files', verbose_name='Föyler')),
                ('is_verified', models.BooleanField(default=False, verbose_name='doğrulandı')),
                ('malzeme', models.ManyToManyField(blank=True, to='Lab.Material')),
            ],
            options={
                'verbose_name_plural': 'Deneyiler',
            },
        ),
        migrations.CreateModel(
            name='DeneyiUygula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masaSayisi', models.IntegerField(default=50)),
                ('a', models.IntegerField(default=20)),
                ('b', models.BooleanField(default=False)),
                ('denenyiSec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab.experiment')),
                ('mazlm', models.ManyToManyField(blank=True, related_name='DeneyiUygulas', to='Lab.Material')),
            ],
        ),
    ]
